from typing import Callable

from django.http import Http404, HttpRequest, HttpResponse


class AdminAccessMiddleware:
    """
    Middleware class to restrict access to admin pages for non-staff users.

    This middleware checks if the requested path contains "admin" and if the user
    making the request is not a staff user. If the conditions are met, a Http404
    exception is raised, indicating that the page is not found.

    Args:
        get_response (callable): The next middleware or view function in the chain.

    Returns:
        HttpResponse: The response generated by the next middleware or view function.

    Raises:
        Http404: If the requested path contains "admin" and the user is not a staff user.
    """

    def __init__(self, get_response: Callable[[HttpRequest], HttpResponse]):
        self.get_response = get_response

    def __call__(self, request: HttpRequest):
        if "admin" in request.path and not request.user.is_staff:
            raise Http404("Page not found")
        response = self.get_response(request)
        return response
