# Generated by Django 5.0 on 2023-12-30 03:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_payment_id', models.CharField(blank=True, max_length=50, verbose_name='stripe ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='paid on')),
                ('subtotal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('tax', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax')),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('requires_payment_method', 'Incomplete')], default='pending', max_length=30)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_payment_method_id', models.CharField(blank=True, max_length=50, verbose_name='stripe ID')),
                ('card_name', models.CharField(max_length=150, verbose_name='name on card')),
                ('type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('paypal', 'PayPal'), ('american_express', 'American Express'), ('discover', 'Discover'), ('diners_club', 'Diners Club'), ('apple_pay', 'Apple Pay'), ('meta_pay', 'Meta Pay'), ('google_pay', 'Google Pay'), ('shop_pay', 'Shop Pay')], max_length=20)),
                ('last_four', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('expiration_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiration_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2023)])),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
        ),
    ]
