# Generated by Django 5.0 on 2023-12-30 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.usermembership', verbose_name='subscription'),
        ),
    ]
