# Generated by Django 4.2.3 on 2023-10-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.usermembership', verbose_name='subscription'),
        ),
    ]
