# Generated by Django 4.2.3 on 2023-10-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_user_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('requires_payment_method', 'Requires_payment_method')], default='pending'),
        ),
    ]
