# Generated by Django 5.0.1 on 2024-02-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
        ('users', '0004_company_customeruser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('requires_payment_method', 'Incomplete')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customeruser', verbose_name='cliente'),
        ),
    ]
