# Generated by Django 4.2.3 on 2023-10-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('requires_payment_method', 'Incomplete')], default='pending'),
        ),
    ]
