# Generated by Django 4.2.3 on 2023-10-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programuser',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
    ]
