from typing import Any

from innovatix.geo_territories.models import Country, Province

def create_country(**kwargs: dict[str, Any]) -> Country: ...
def create_province(country: Country, **kwargs: dict[str, Any]) -> Province: ...
def get_default_country() -> Country: ...
def get_default_province() -> Province: ...
