# Generated by Django 5.0 on 2024-02-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='company',
        ),
    ]
