# Generated by Django 5.0 on 2024-02-03 16:17

import django.db.models.deletion
import innovatix.geo_territories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_territories', '0001_initial'),
        ('users', '0003_remove_customeruser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('zip', models.CharField(max_length=5, verbose_name='zip code')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('posting_frequency', models.CharField(max_length=100, verbose_name='posting frequency')),
                ('is_individual', models.BooleanField(default=False, verbose_name='is individual')),
                ('country', models.ForeignKey(default=innovatix.geo_territories.utils.get_default_country, on_delete=django.db.models.deletion.PROTECT, to='geo_territories.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo_territories.province', verbose_name='state')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AddField(
            model_name='customeruser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='company'),
        ),
    ]
