# Generated by Django 5.0.1 on 2024-02-09 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import innovatix.core.services.phone_number_service
import innovatix.geo_territories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_territories', '0001_initial'),
        ('users', '0004_company_customeruser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='accept_email_marketing',
            field=models.BooleanField(default=True, verbose_name='Cliente aceptó recibir correos electrónicos de marketing.'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='accept_sms_marketing',
            field=models.BooleanField(default=True, help_text='Debes pedir permiso a tus clientes antes de suscribirlos a tus correos electrónicos o mensajes de texto de marketing.', verbose_name='Cliente aceptó recibir mensajes de texto de marketing por SMS.'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='accept_terms_condition',
            field=models.BooleanField(default=False, verbose_name='Cliente aceptó los Términos y Condiciones.'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='address1',
            field=models.CharField(max_length=150, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='address2',
            field=models.CharField(blank=True, max_length=150, verbose_name='apartamento, suite, etc.'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='city',
            field=models.CharField(max_length=75, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='compañía'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='country',
            field=models.ForeignKey(default=innovatix.geo_territories.utils.get_default_country, on_delete=django.db.models.deletion.PROTECT, to='geo_territories.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un usuario con ese email ya existe.'}, help_text='Requerido. 150 caracteres o menos.', max_length=150, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='external_customer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID de Stripe'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(max_length=72, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designa si este usuario debe ser tratado como activo. Anule la selección en lugar de eliminar cuentas.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='langugage',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=30, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(max_length=72, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='notes',
            field=models.TextField(blank=True, help_text='Agrega notas sobre tu cliente.', verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='partner_number',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_partner_number', message="El número de socio debe estar en el formato: 'YYYY-MM-####'", regex='^\\d{4}-\\d{2}-\\d{4}$')], verbose_name='número de socio'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='pay_tax',
            field=models.BooleanField(default=True, verbose_name='Recolectar impuesto'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[innovatix.core.services.phone_number_service.PhoneNumberService.validate_phone_number], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo_territories.province', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Las etiquetas se pueden usar para categorizar a los clientes en grupos.', to='users.tag'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='zip',
            field=models.CharField(max_length=5, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un usuario con ese email ya existe.'}, help_text='Requerido. 150 caracteres o menos.', max_length=150, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='first_name',
            field=models.CharField(max_length=72, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designa si este usuario debe ser tratado como activo. Anule la selección en lugar de eliminar cuentas.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='last_name',
            field=models.CharField(max_length=72, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='programuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[innovatix.core.services.phone_number_service.PhoneNumberService.validate_phone_number], verbose_name='Teléfono'),
        ),
    ]
