# Generated by Django 5.0.1 on 2024-02-16 21:59

import innovatix.core.services.phone_number_service
import innovatix.users.models.customer_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customeruser_accept_email_marketing_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', innovatix.users.models.customer_user.CustomerUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='posting_frequency',
        ),
        migrations.AddField(
            model_name='company',
            name='preferences',
            field=models.TextField(blank=True, default='', verbose_name='preferences'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, validators=[innovatix.core.services.phone_number_service.PhoneNumberService.validate_phone_number], verbose_name='phone'),
        ),
    ]
