# Generated by Django 5.0.1 on 2024-02-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customeruser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
