# Generated by Django 5.0.1 on 2024-03-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_territories', '0001_initial'),
        ('users', '0008_alter_customeruser_options_customeruser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geo_territories.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='province',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.PROTECT, to='geo_territories.province', verbose_name='estado'),
        ),
    ]
