# Generated by Django 4.2.3 on 2023-10-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stripe ID'),
        ),
    ]
