# Generated by Django 4.2.3 on 2023-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_membership_external_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='external_product_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='stripe ID'),
            preserve_default=False,
        ),
    ]
